### ISSUE TITLE
Map is now missing zone & continent drop down boxes.

### ISSUE THREAD

**Issue by MurderOnMyMind7** [GoldpawsStuff/ClassicWorldMapEnhanced#13]
Hello, 

I hate to be a bother, but I'm a HUGE fan of this addon; it's by the cleanest map addon with some very nice quality of life features. As of yesterday, I updated some addons and downloaded DBM. (I'm not sure if DBM had some interaction or not) Regardless, when I opened the map I noticed that the "hide questie button" moved over to the top right of the map covering the "fog of war checkbox" and the [zone] and [continent] dropdown boxes disappeared. This is the first time I've EVER had an issue with the addon and I'd love to get it back to being perfect. I tired uninstalling, reinstalling, deleting it & /reloading in game. I even uninstalled DBM haha I'm not sure what else I can do. Anyway, I hate to be a bother and I'm sure you're very busy Goldpaw, but if you could get back to me at some point and try to help me out, I'd GREATLY appreciate it! <3 I PM'd you on Curse, but I noticed you had a page here so I wasn't sure what you preferred. Sorry if this was long-winded lol. Have a great day :D

**Comment by goldpaw** [comment]
So I deleted my old Questie folders and manually downloaded and installed the new ones from CurseForge, to make sure I was updated and no old files were messing up things. I was unsure whether you were using the classic 60 or classic tbc version, so I tried both. The TBC one works fine. The Classic "Era" one indeed has the "Hide Questie" button covering the "Fog of War" button. 

Man that's annoying! And it covers it PERFECTLY!?! 

I'll add a workaround and place it differently if Questie is enabled! Until that, you can hold your mouse directly on the "Hide Questie" button, open the chat with Enter, and type `/run GetMouseFocus():Hide()` and hit Enter in the chat. That'll hide whatever is under the mouse cursor, and voila, "Fog of War checkbox" is visible!

**Comment by goldpaw** [comment]
Got a fix that adjusts our checkbox when the questie button moves! Uploading it now! :) 

![WoWScrnShot_091921_184732](https://user-images.githubusercontent.com/6476535/133935818-4eb25bc4-b043-4546-a4fd-4e607b6bf53f.jpg)

![WoWScrnShot_091921_184733](https://user-images.githubusercontent.com/6476535/133935820-d57aff21-484e-424a-9275-2d07e63c9744.jpg)

**Comment by goldpaw** [comment]
Fixed in 1.2.20, which should be available on CurseForge shortly.
