### ISSUE TITLE
wierd hovering

### ISSUE THREAD

**Issue by Robertox92** [GoldpawsStuff/ClassicWorldMapEnhanced#6]
whenever I try to go to click on a place I have to figure it out on where to click. There's a link on how it looks.

Thank you!

https://gyazo.com/cab0bd1772aa7b001fb87800d1adf5d0

**Comment by goldpaw** [comment]
This error report is lacking a little info. Have you tried with no other addons enabled? Because this seems like some other addon is trying to control the worldmap too, perhaps?

**Comment by goldpaw** [comment]
Should be fixed ages ago, I've just forgotten to close this thread.
