### ISSUE TITLE
TBC Beta / TBC version plans?

### ISSUE THREAD

**Issue by runboy93** [GoldpawsStuff/ClassicWorldMapEnhanced#7]
Do you have any plans for TBC Beta / TBC (2.5.1+) version of this awesome addon?

**Comment by goldpaw** [comment]
We'll see when I get TBC access or TBC goes live. I'm not in the beta, so I can't say. All depends on the route Blizzard has taken with their new TBC UI. 

What I _can_ say is that I'll most likely will convert either this, or my similar (yet even cleaner loooking) fullscreen map shrinking addon for retail (MapShrinker) to work with TBC. Which one comes down to what code Blizzard used as a base for their TBC worldmap.

**Comment by runboy93** [comment]
Well, there is confirmed date for prepatch in 18. May (and launch 1st june or 2nd, depends on your location)

**Comment by runboy93** [comment]
PTR (Classic) have been updated to 2.5.1 and is free for all to test.
