### ISSUE TITLE
Incompatability?

### ISSUE THREAD

**Issue by SCW5000** [GoldpawsStuff/ClassicWorldMapEnhanced#8]
Is your addon not compatible with Questie?  I noticed the fade feature does not work when moving with Questie.

**Comment by goldpaw** [comment]
Works just fine for me. Full opacity when standing still, semi-faded when moving. 

![WoWScrnShot_043021_225050](https://user-images.githubusercontent.com/6476535/116752956-a209a980-aa06-11eb-8073-b71353f98b99.jpg)
![WoWScrnShot_043021_225119](https://user-images.githubusercontent.com/6476535/116752966-a46c0380-aa06-11eb-9ff9-4ba9af7efc32.jpg)
![WoWScrnShot_043021_225122](https://user-images.githubusercontent.com/6476535/116752973-a635c700-aa06-11eb-93ff-c73bf63a4e10.jpg)

**Comment by runboy93** [comment]
Yeah I can also confirm it works with questie. Personally I think that fade effect could be improved more on moving (close to that you see your character through map, now map takes little more from screen)

**Comment by goldpaw** [comment]
I can lower the alpha to 50% when moving, the same as it is in retail. It's currently on 65%, which was fine in daylight in bright Silithus when I made it, but I can see how that's a little too opaque for night or raid scenes. ;)

**Comment by goldpaw** [comment]
Still not incompatible with questie, though. So closing this issue! The alpha change should be live on curseforge/overwolf/wago in a few minutes'ish. :)
